name: Check Epic Games
on:
  workflow_dispatch:
  schedule:
    # - cron:  '30 23 * * THU'
    # weekly regular epic games schedule
    - cron: '30 23 * 1-11 THU'
    # - cron: '30 23 1-12,29-31 12 THU'
    # 15 days of december mystery games (daily)
    # - cron: '30 23 13-28 12 *'
    - cron:  '30 23 * 12 WED'
  # push:

jobs:
  check_free_games:
    name: Check Epic Games Freebies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.12

      - name: Install dependencies
        run: npm ci

      - name: Run
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node index.js

      - name: Notify on failure
        if: ${{ failure() }}
        env:
          DISCORD_MESSAGE: "Workflow failed at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"username": "Github Actions", "content": "$DISCORD_MESSAGE"}' \
          "${{ secrets.DISCORD_ALERTS_WEBHOOK }}"

