name: Build container image
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - src/**
      - package.json
      - Dockerfile

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.17

      - name: Install dependencies
        run: npm ci

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ github.repository }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Notify on failure
        if: ${{ failure() }}
        env:
          DISCORD_MESSAGE: "Workflow failed at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"username": "${{ github.repository }}/${{ github.workflow }}", "content": "$DISCORD_MESSAGE"}' \
          "${{ secrets.DISCORD_ALERTS_WEBHOOK }}"

